---
#
# Installing Java 8
#
# Add the Java ppa repository
- name: Add Java repository
 apt_repository:
   repo: ppa:webupd8team/java
# Automatically accepts the Oracle License popup in the terminal
- name: Automatically select the Oracle License
 shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
# Install Java 8
- name: Install the Java 8 package
 apt:
   name: oracle-java8-installer
   state: present
   update_cache: yes
# Installing Kibana
#
# Add Kibana APT-repository
- name: Adding Kibana APT repository
 apt_repository:
   repo: deb http://packages.elastic.co/kib... stable main
   state: present
# Install Kibana
- name: Update repositories cache and install Kibana
 apt:
   name: kibana
   update_cache: yes
# Update kibana config file to only accept local connections
- name: Updating the config file to restrict outside access
 lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.host:'
   line: 'server.host: localhost'
# Enable Kibana service
- name: Enabling Kibana service
 systemd:
   name: kibana
   enabled: yes
   daemon_reload: yes
# Start Kibana service
- name: Starting Kibana service
 systemd:
   name: kibana
   state: started