---
# The hostname of the server that is going to run the ELK stack
server_name: elk
# -- Nginx Variables --
# The port that Nginx listens to that is forwarded to Kibana's local port
nginx_kibana_port: 80
# Nginx SSL listening port
elk_server_ssl_cert_port: 8080
# The web authentication credentials to gain access to Kibana
kibana_user: admin
kibana_password: admin
# The system user that Nginx will use
nginx_user: www-data
# The IP address of the ELK server that is going to be installed
e_ip: 192.168.2.217
k_ip: 192.168.2.134
l_ip: 192.168.2.51

#ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ProxyCommand="ssh -A  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null  -W %h:%p -q ubuntu@3.142.201.147"'
ansible_ssh_common_args: '-i ~/.ssh/group-3.pem -J ubuntu@3.142.201.147'
ansible_ssh_private_key_file: '~/.ssh/group-3.pem'
